routes/admin.php
<?php


Route::get('home', 'HomeController@index')->name('home.index');

Route::resource('estados', 'EstadoController');

Route::resource('areas', 'AreaController');

Route::resource('tipos_tramite', 'TipoTramiteController');

Route::resource('tramites', 'TramiteController');

Route::resource('cargos', 'CargoController');

Route::get('register', 'RegisterControlleAuth\r@showRegistrationForm')->name('register');

Route::get('cargo/usuario/create/{usuario}', 'CargoUsuarioController@create')->name('cargo_usuario.create');
Route::get('cargo/usuario/show/{usuario}', 'CargoUsuarioController@show')->name('cargo_usuario.show');
Route::post('cargo/usuario/store/{usuario}', 'CargoUsuarioController@store')->name('cargo_usuario.store');

routes/web.php
<?php

Route::group(['middleware' => 'guest'], function () {

    // Authentication Routes...
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');

    // Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');

});


Route::group(['middleware' => 'auth'], function () {

    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index')->name('home');

    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    Route::group(['middleware' => 'admin', 'as' => 'admin.', 'prefix' => 'admin'], function () {

        // Users Routes...
        Route::get('usuario', 'Auth\RegisterController@index')->name('usuario.index');

        Route::post('usuario', 'Auth\RegisterController@store')->name('usuario.store');

        Route::get('usuario/create', 'Auth\RegisterController@createForm')->name('usuario.create');

    });
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected $fillable = [
        'name', 'lastname', 'email', 'area', 'password', 'fecha_nacimiento'
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $appends = 'usuario';

    public function setFechaNacimientoAttribute($value)
    {
        $this->attributes['fecha_nacimiento'] = date('Y-m-d', strtotime($value));
    }

    public function setNameAttribute($value){
        $this->attributes['name'] = ucwords(strtolower($value));
    }

    public function getFechaNacimientoAttribute(){
        return date('Y-m-d', strtotime($this->fecha_nacimiento));
    }

    public function getUsuarioAttribute(){
        return "$this->name $this->lastname";
    }

    /*
     * RELACIONES
     */

    public function telefono()
    {
        return $this->hasOne(Telefono::class);
    }


    public function cargos(){
        return $this->belongsToMany(Cargo::class,'cargo_user')
            ->withPivot(['fecha_inicio']);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::get();

        return view('admin.users.index', compact('users'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

//        dd()

        Validator::make($request->all(), [
            'name' => 'required|string|max:30',
            'lastname' => 'required|string|max:30',
            'email' => 'required|string|email|max:100|unique:users',
            'area' => 'required|string|max:20',
            'password' => 'required|string|min:6|confirmed',
        ])->validate();

        User::create([
            'name' => $request->input('name'),
            'lastname' => $request->input('lastname'),
            'email' => $request->input('email'),
            'area' => $request->input('area'),
            'password' => Hash::make($request->input('password')),
        ]);

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::find($id)->delete();

        $users = User::get();

        return view('admin.users.index', compact('users'));
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.admin')

@section('title')

    Registro

@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">

                    <div class="card-body">

                        <form method="POST" action="{{ route('admin.usuario.store') }}">

                            @csrf

                            <div class="form-group row">

                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text"
                                           class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                           name="name" value="{{ old('name') }}"
                                           required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">

                                <label for="lastname"
                                       class="col-md-4 col-form-label text-md-right">{{ __('LastName') }}</label>

                                <div class="col-md-6">
                                    <input id="lastname" type="text"
                                           class="form-control{{ $errors->has('lastname') ? ' is-invalid' : '' }}"
                                           name="lastname"
                                           value="{{ old('lastname') }}" required>

                                    @if ($errors->has('lastname'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('lastname') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-6">
                                    <label for="name">Fecha de nacimiento</label>

                                    <input id="fecha_nacimiento" type="text"
                                           class="form-control fecha_nacimiento"
                                           autocomplete="off"
                                           name="fecha_nacimiento" value="{{ old('fecha_nacimiento') }}" required>
                                </div>

                                <div class="col-md-6">
                                    <label for="name">Teléfono (Opcional)</label>

                                    <input id="telefono" type="text"
                                           class="form-control"
                                           name="telefono" value="{{ old('telefono') }}">
                                </div>

                            </div>

                            <div class="form-group row">
                                <label for="email"
                                       class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                <div class="col-md-6">
                                    <input id="email" type="email"
                                           class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}"
                                           name="email"
                                           value="{{ old('email') }}" required>

                                    @if ($errors->has('email'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">

                                <label for="area" class="col-md-4 col-form-label text-md-right">{{ __('Area') }}</label>

                                <div class="col-md-6">
                                    <input id="area" type="text"
                                           class="form-control{{ $errors->has('area') ? ' is-invalid' : '' }}"
                                           name="area" value="{{ old('area') }}"
                                           required>


                                    @if ($errors->has('area'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('area') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password"
                                       class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password" type="password"
                                           class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}"
                                           name="password"
                                           required>

                                    @if ($errors->has('password'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password-confirm"
                                       class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password-confirm" type="password" class="form-control"
                                           name="password_confirmation" required>
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Register') }}
                                    </button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>

@endsection

resources/views/admin/users/destroy.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: orejasnb
 * Date: 10/23/18
 * Time: 8:20 AM
 */

resources/views/admin/users/edit.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: orejasnb
 * Date: 10/23/18
 * Time: 8:20 AM
 */

resources/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('title')
    Usuarios
@endsection

@section('link')
    <li class="breadcrumb-item active">
        <a href="{{route('admin.usuario.index')}}">Usuarios</a>
    </li>
@endsection

@section('content')


    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h5 class="m-0">Lista de usuarios</h5>
            </div>
            <div class="card-body">

                <table class="table table-bordered ">
                    <thead class="thead-dark">
                    <tr>
                        <th class="text-center">Usuario</th>
                        <th class="text-center">Telefono</th>
                        <th class="text-center">Email</th>
                        <th class="text-center">Rol</th>
                        <th class="text-center">Cargos</th>
                        <th class="text-center">
                            <a class="btn btn-primary btn-sm" href="{{route('admin.usuario.create')}}">Nuevo usuario</a>
                        </th>
                    </tr>
                    </thead>

                    <tbody class="text-center">
                    @foreach($users as $user)
                        <tr>
                            <td>{{$user->usuario}}</td>
                            <td>
                                @if($user->telefono)
                                    {{$user->telefono->telefono}}
                                @else
                                    <p class=" badge badge-danger">
                                        No tiene teléfono
                                    </p>
                                @endif

                            </td>
                            <td>{{$user->email}}</td>
                            <td>{{$user->role}}</td>
                            <td>
                                @if($user->cargos)
                                    @foreach($user->cargos as $cargo)
                                        <span class="badge badge-success" style="font-size: 15px;">{{$cargo->cargo}}</span> <br>
                                    @endforeach
                                @endif

                            </td>
                            <td class="text-center">
                                <div class="btn-group">
                                    <i class="fa fa-list" aria-hidden="true" data-toggle="dropdown"
                                       aria-expanded="false" style="cursor: pointer; color: #1d68a7">
                                    </i>

                                    <div class="dropdown-menu" role="menu" x-placement="bottom-start"
                                         style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(67px, 38px, 0px);">
                                        <a class="dropdown-item" href="{{route('admin.cargo_usuario.create', $user->id)}}">
                                            <i class="fa fa-pencil-alt" ></i>
                                            Agregar Cargo
                                        </a>
                                        <a class="dropdown-item" href="{{route('admin.cargo_usuario.show', $user->id)}}">
                                            <i class="fa fa-pencil-alt" aria-hidden="true"></i>
                                            Eliminar Cargo
                                        </a>
                                        <a class="dropdown-item" href="">
                                            <i class="fa fa-pencil-alt" aria-hidden="true"></i>
                                            Editar
                                        </a>
                                        <a class="dropdown-item" href="#">
                                            <i class="fa fa-trash" aria-hidden="true"></i>
                                            Eliminar
                                        </a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection